#!/bin/sh

exec chpst -u postgres:postgres \
    /usr/lib/postgresql/10/bin/postgres \
        -D /var/lib/postgresql/data \
        -c config_file=/etc/postgresql/postgresql.conf \
        -c hba_file=/etc/postgresql/pg_hba.conf
